{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

	<div class="control-group">
		<label class="control-label" for="id_{{$field.0}}">{{$field.1}}</label>
		<p>Debug: {{$field.2}}</p>
		<div class="controls">
			<div class="switch" data-on-label="{{if $field.4}}{{$field.4.1}}{{else}}ON{{/if}}" data-off-label="{{if $field.4}}{{$field.4.0}}{{else}}OFF{{/if}}">
				<input id="id_{{$field.0}}" type="checkbox" id='id_{{$field.0}}' value="{{$field.2}}" {{if $field.2}} checked {{/if}} />
			</div>
		</div>
		<span class='field_help'>{{$field.3}}</span>
	</div>
