{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
	
        <div class="control-group">
		<label class="control-label" for='id_{{$field.0}}'>{{$field.1}}</label>
		<div class='switch'>
			<input type="checkbox" name='{{$field.0}}' id='id_{{$field.0}}' value="{{$field.3}}" {{if $field.2}}checked="true"{{/if}}>
		</div>
		<span class='field_help'>{{$field.4}}</span>
	</div>
