{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
    <div class="navbar fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav-collapse collapse">
		<a class="brand" href="#">{{$banner}}</a> 

            <ul class="nav">
        {{if $userinfo}}
                <li id="nav-user-linkmenu" class="nav-menu-icon dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="#nav-user-menu" title="{{$userinfo.name}}"><img src="{{$userinfo.icon}}" alt="{{$userinfo.name}}"></a>
                {{if $localuser}}
                        <ul id="nav-user-menu" class="dropdown-menu">
                                {{foreach $nav.usermenu as $usermenu}}
                                        <li><a class="{{$usermenu.2}}" href="{{$usermenu.0}}" title="{{$usermenu.3}}">{{$usermenu.1}}</a></li>
                                {{/foreach}}
                                {{if $nav.profiles}}<li><a class="{{$nav.profiles.2}}" href="{{$nav.profiles.0}}" title="{{$nav.profiles.3}}">{{$nav.profiles.1}}</a></li>{{/if}}
                                {{if $nav.manage}}<li><a class="{{$nav.manage.2}}" href="{{$nav.manage.0}}" title="{{$nav.manage.3}}">{{$nav.manage.1}}</a></li>{{/if}}
                                {{if $nav.contacts}}<li><a class="{{$nav.contacts.2}}" href="{{$nav.contacts.0}}" title="{{$nav.contacts.3}}" >{{$nav.contacts.1}}</a></li>{{/if}}
                                {{if $nav.settings}}<li><a class="{{$nav.settings.2}}" href="{{$nav.settings.0}}" title="{{$nav.settings.3}}">{{$nav.settings.1}}</a></li>{{/if}}

                                {{if $nav.admin}}<li><a class="{{$nav.admin.2}}" href="{{$nav.admin.0}}" title="{{$nav.admin.3}}" >{{$nav.admin.1}}</a></li>{{/if}}

                                {{if $nav.logout}}<li><a class="menu-sep {{$nav.logout.2}}" href="{{$nav.logout.0}}" title="{{$nav.logout.3}}" >{{$nav.logout.1}}</a></li>{{/if}}

                        </ul>
                {{/if}}
                </li>
        {{/if}}

        {{if $nav.lock}}
                <li id="nav-rmagic-link" class="nav-menu-icon" >
                        <a class="icon {{$nav.lock.2}}" href="{{$nav.lock.0}}" title="{{$nav.lock.3}}" >{{$nav.lock.1}}</a>
                </li>
        {{/if}}
        {{if $nav.network}}
                <li id="nav-network-link" class="dropdown">
                        <a href="{{$nav.network.0}}"><span class="icon-group" data-toggle="tooltip" title="{{$nav.network.1}}"></span></a><span id="net-update" href="#" class="badge badge-info notify-badge dropdown-toggle" data-toggle="dropdown" rel="#nav-network-menu"></span>
                        <ul id="nav-network-menu" class="dropdown-menu" rel="network">
				<li><a class="{{$nav.network.2}}" href="{{$nav.network.0}}" title="{{$nav.network.3}}" ><span class="icon-group"></span> {{$nav.network.1}}</a></li> 
                                <li id="nav-network-see-all"><a href="{{$nav.network.all.0}}">{{$nav.network.all.1}}</a></li>
                                <li id="nav-network-mark-all"><a href="#" onclick="markRead('network'); return false;">{{$nav.network.mark.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                        </li>
        {{/if}}

        {{if $nav.home}}
                <li id="nav-home-link" class="dropdown">
                        <a href="{{$nav.home.0}}"><span class="icon-user" data-toggle="tooltip" title="{{$nav.home.1}}"></span></a><span class="badge badge-info notify-badge dropdown-toggle" rel="#nav-home-menu id="home-update" class="dropdown-toggle" data-toggle="dropdown"></span>
                        <ul id="nav-home-menu" class="dropdown-menu notify-menus" rel="home">
 		               <li><a class="{{$nav.home.2}}" href="{{$nav.home.0}}" title="{{$nav.home.3}}" ><span class="icon-user"></span> {{$nav.home.1}}</a></li>
                                <li id="nav-home-see-all"><a href="{{$nav.home.all.0}}">{{$nav.home.all.1}}</a></li>
                                <li id="nav-home-mark-all"><a href="#" onclick="markRead('home'); return false;">{{$nav.home.mark.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                </li>
        {{/if}}

   {{if $nav.register}}<li id="nav-register-link" class="nav-menu {{$nav.register.2}}"><a href="{{$nav.register.0}}" title="{{$nav.register.3}}" >{{$nav.register.1}}</a><li>{{/if}}

        {{if $nav.messages}}
                <li id="nav-mail-link" class="dropdown">
                        <a href="{{$nav.messages.0}}"><span class="icon-envelope-alt" data-toggle="tooltip" title="{{$nav.messages.1}}"></span></a><span class="badge badge-info notify-badge dropdown-toggle" rel="#nav-messages-menu id="mail-update" class="dropdown-toggle" data-toggle="dropdown"></span>
                        <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="#nav-messages-menu"><span class="icon-envelope-alt" data-toggle="tooltip" title="{{$nav.messages.1}}"></span><span id="mail-update" class="nav-notify fakelink" rel="#nav-messages-menu"></span></a>-->
                        <ul id="nav-messages-menu" class="dropdown-menu notify-menus" rel="messages">
<!--	                        <a class="{{$nav.messages.2}}" href="{{$nav.messages.0}}" title="{{$nav.messages.3}}" >{{$nav.messages.1}}</a>-->
                                <li id="nav-messages-see-all"><a href="{{$nav.messages.all.0}}">{{$nav.messages.all.1}}</a></li>
                                <li id="nav-messages-mark-all"><a href="#" onclick="markRead('messages'); return false;">{{$nav.messages.mark.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                </li>
        {{/if}}

        {{if $nav.all_events}}
                <li id="nav-all_events-link" class="dropdown">
                        <a href="{{$nav.all_events.0}}"><span class="icon-calendar" data-toggle="tooltip" title="{{$nav.all_events.1}}"></span></a><span class="badge badge-info notify-badge dropdown-toggle" rel="#nav-all_events-menu id="all_events-update" class="dropdown-toggle" data-toggle="dropdown"></span>

<!--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="#nav-all_events-menu"><span class="icon-calendar" data-toggle="tooltip" title="{{$nav.all_events.1}}"></span><span id="all_events-update" class="nav-notify fakelink" rel="#nav-all_events-menu"></span></a>-->
                        <ul id="nav-all_events-menu" class="dropdown-menu notify-menus" rel="all_events">
<!--	                        <a class="{{$nav.all_events.2}}" href="{{$nav.all_events.0}}" title="{{$nav.all_events.3}}" >{{$nav.all_events.1}}</a>-->
                                <li id="nav-all_events-see-all"><a href="{{$nav.all_events.all.0}}">{{$nav.all_events.all.1}}</a></li>
                                <li id="nav-all_events-mark-all"><a href="#" onclick="markRead('all_events'); return false;">{{$nav.all_events.mark.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                </li>
        {{/if}}

        {{if $nav.intros}}
                <li id="nav-intros-link" class="dropdown">
                        <a href="{{$nav.intros.0}}"><span class="icon-exchange" data-toggle="tooltip" title="{{$nav.intros.1}}"></span></a><span class="badge badge-info notify-badge dropdown-toggle" rel="#nav-intros-menu id="intro-update" class="dropdown-toggle" data-toggle="dropdown"></span>

<!--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="#nav-intros-menu"><span class="icon-exchange" data-toggle="tooltip" title="{{$nav.intros.1}}"></span><span id="intro-update" class="badge badge-info" rel="#nav-intros-menu"></span></a>-->
                        <ul id="nav-intros-menu" class="dropdown-menu notify-menus" rel="intros">
<!--	                        <a class="{{$nav.intros.2}}" href="{{$nav.intros.0}}" title="{{$nav.intros.3}}" >{{$nav.intros.1}}</a>-->
                                <li id="nav-intros-see-all"><a href="{{$nav.intros.all.0}}">{{$nav.intros.all.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                </li>
        {{/if}}

        {{if $nav.notifications}}
                <li id="nav-notify-linkmenu" class="dropdown">
                        <a href="{{$nav.notifications.0}}"><span class="icon-bell-alt" data-toggle="tooltip" title="{{$nav.notifications.1}}"></span></a><span id="notify-update" href="#" class="badge badge-info notify-badge dropdown-toggle" data-toggle="dropdown" rel="#nav-notify-menu"></span>

<!--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="#nav-notify-menu"><span class="icon-bell-alt" data-toggle="tooltip" title="{{$nav.notifications.1}}"></span><span id="notify-update" class="badge badge-info" rel="#nav-notify-menu"></span></a>-->
                        <ul id="nav-notify-menu" class="dropdown-menu notify-menus" rel="notify">
<!--	                        <a href="{{$nav.notifications.0}}" title="{{$nav.notifications.1}}">{{$nav.notifications.1}}</a>-->
                                <li id="nav-notify-see-all"><a href="{{$nav.notifications.all.0}}">{{$nav.notifications.all.1}}</a></li>
                                <li id="nav-notify-mark-all"><a href="#" onclick="markRead('notify'); return false;">{{$nav.notifications.mark.1}}</a></li>
                                <li class="empty">{{$emptynotifications}}</li>
                        </ul>
                </li>
        {{/if}}
        {{if $nav.login}}<li id="nav-login-link" class="nav-menu {{$nav.login.2}}"><a href="{{$nav.login.0}}" title="{{$nav.login.3}}" >{{$nav.login.1}}</a><li>{{/if}}
        {{if $nav.alogout}}<li id=nav-alogout-link" class="nav-menu {{$nav}}-alogout.2"><a href="{{$nav.alogout.0}}" title="{{$nav.alogout.3}}" >{{$nav.alogout.1}}</a></li>{{/if}}

        {{if $nav.directory}}
                <li id="nav-directory-link" class="nav-menu {{$sel.directory}}">
			<a class="{{$nav.directory.2}}" href="{{$nav.directory.0}}" title="{{$nav.directory.3}}"><span class="icon-folder-open"></span></a>
                </li>
        {{/if}}

        {{if $nav.help}}
                <li id="nav-help-link" class="nav-menu {{$sel.help}}">
                        <a class="{{$nav.help.2}}" target="friendika-help" href="{{$nav.help.0}}" title="{{$nav.help.3}}" ><span class="icon-question-sign"></span></a>
                </li>
        {{/if}}

        {{if $nav.apps}}
                <li id="nav-apps-link" class="nav-menu {{$sel.apps}}">
                        <a class=" {{$nav.apps.2}}" href="#" rel="#nav-apps-menu" title="{{$nav.apps.3}}" >{{$nav.apps.1}}</a>
                        <ul id="nav-apps-menu" class="menu-popup">
                        {{foreach $apps as $ap}}
                                <li>{{$ap}}</li>
                                {{/foreach}}
                        </ul>
                </li>
        {{/if}}

                <li id="nav-searchbar">
                        <form method="get" action="search">
                                <input id="nav-search-text" type="text" value="" placeholder="{{$nav.search.1}}" name="search" title="{{$nav.search.3}}" onclick="this.submit();" />
                        </form>
                </li>
		<b id="nav-search-spinner" class='icon-spinner icon-spin icon-2x' style="display:none;"></b>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

<ul id="nav-notifications-template" style="display:none;" rel="template">
	<li class="{4}"><a href="{0}"><img src="{1}">{2} <span class="notif-when">{3}</span></a></li>
</ul>

<div id="langselector" >{{$langselector}}</div>
<div id="panel" style="display: none;"></div>
